# Generated by Django 4.1.4 on 2023-01-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='drill',
        ),
    ]
