# Generated by Django 4.1.4 on 2023-01-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_component_drill'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='drill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.drill'),
        ),
    ]
